### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asynts** [asynts/micro#1]
Server
---
- [ ] Use two threads for each accepted connection (listen on tcp / listen on channel).
- [ ] Put the connections into an iterator (circle?) and use some `try_recv()` function.
- [ ] Create a macro for client log messages `cmsg!(id, msg, ...)`

Client
---
- [ ] Don't panic if there is no message in the queue.
